jaoFe:
  jaoFe:
    image:
      repository: ir1313/jao-fe
      tag: 0.0.1
    imagePullPolicy: Always
  replicas: 1
kubernetesClusterDomain: cluster.local
service:
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
