apiVersion: v1
kind: Service
metadata:
  name: {{ include "jao.fullname" . }}-fe-service
  labels:
  {{- include "jao.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: jao-fe
  {{- include "jao.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 -}}